### ISSUE TITLE
Calling a gRPC service results in status code 2: "No status received"

### ISSUE THREAD

**Issue by xiaozhongliu** [grpc/grpc-node#1569]
### Problem description
Error occurs when calling a gRPC service which is behind the istio gateway:
![image](https://user-images.githubusercontent.com/17674404/92848116-7c4e7680-f41c-11ea-9eb5-f00b035217c7.png)

But it's ok if I use go client to request. Below are the results for several situations:
go client => gRPC service ✅
node client => gRPC service ✅
go client => gateway => gRPC service ✅
node client => gateway => gRPC service ❎

### Reproduction steps
server: any valid server
gateway:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-isolated
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - k8s-demo-grpc.internal.sample.com
      port:
        name: grpc
        number: 80
        protocol: GRPC
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8s-demo-grpc-isolated
  namespace: stage-c1
spec:
  hosts:
    - k8s-demo-grpc.internal.sample.com
  gateways:
    - default/gateway-isolated
  http:
    - route:
        - destination:
            host: k8s-demo-grpc
```
node client:
```js
const proto = './helloworld.proto'
const address = 'k8s-demo-grpc.internal.sample.com:80'
const service = 'Greeter'
const method = 'sayHello'
const data = { name: 'world' }
const deadline = Date.now() + 1000

const grpc = require('grpc')
const protoLoader = require('@grpc/proto-loader')

const packageDefinition = protoLoader.loadSync(proto, {
    keepCase: true,
    longs: String,
    enums: String,
    defaults: true,
    oneofs: true,
})
const pack = grpc.loadPackageDefinition(packageDefinition).helloworld

function main() {
    const client = new pack[service](address, grpc.credentials.createInsecure())
    client[method](data, { deadline }, (err, response) => {
        if (err) return console.log(err)
        console.log('response:', response)
    })
}
main()
```

### Environment
 - OS name, version and architecture: any
 - Node version: 10.15.3
 - Node installation method: docker image registry.cn-hangzhou.aliyuncs.com/aliyun-node/alinode:4.7.2-alpine
 - If applicable, compiler version: unknown
 - Package name and version: grpc@1.24.3
