### ISSUE TITLE
Step #0: error @grpc/grpc-js@0.4.3: The engine "node" is incompatible with this module. Expected version "^8.13.0 || >=10.10.0".

### ISSUE THREAD

**Issue by skhaz** [grpc/grpc-node#913]
### Problem description

I'm trying to use Google Cloud Build with my Firebase project, in the very first step

```
steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
```

I got:

```
Step #0: error @grpc/grpc-js@0.4.3: The engine "node" is incompatible with this module. Expected version "^8.13.0 || >=10.10.0".
```

### Reproduction steps

Create a `cloudbuild.yaml` with the following content:

```yaml
steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']
- name: 'gcr.io/$PROJECT_ID/yarn'
  args: ['deploy:ci']
```

Create a `package.json` with the following content:

```json
{
  "private": true,
  "devDependencies": {
    "firebase-tools": "^6.11.0",
  },
  "dependencies": {
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^2.3.1",
  },
  "engines": {
    "node": "8"
  },
  "scripts": {
    "deploy": "firebase deploy --force --only functions",
  }
}
```

### Environment

Google Cloud Build

### Additional context

N/A
